// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


console.log("Hello, BuckleScript");

function sum(lst) {
  var _acc = 0;
  var _param = lst;
  while(true) {
    var param = _param;
    var acc = _acc;
    if (param) {
      _param = param[1];
      _acc = acc + param[0] | 0;
      continue ;
    } else {
      return acc;
    }
  };
}

exports.sum = sum;
/*  Not a pure module */
